### ISSUE TITLE
Odd rendering on non-markdown'd rants

### ISSUE THREAD

**Issue by scriptcoded** [devTeaa/devrant-markdown#1]
**Describe the bug**

**To Reproduce**
1. Go to https://devrant.com/rants/1971290/thinking-of-adding-a-few-aliases-bashrc-custom-aliases-daddy-shark-doo-doo-doo-d
2. Try both with and without devrant-markdown enabled.
3. Markdown renders oddly (technically correctly though)

**Expected behavior**
This is kind of a hard one since one would usually put code inside ` ```code``` `. Perhaps there should be some sort of decision making algorithm that decides whether or not to highlight certain parts of the text.

An alternative solution would be to require som sort of trigger in the rant to enable the markdown highlighter. Putting ~md at the start or adding it as a tag. That would mean that only rants with markdown would be parsed.

**Screenshots**
![screenshot_5](https://user-images.githubusercontent.com/6452991/51682225-26c71b00-1fe7-11e9-8c9a-af807ab5afeb.png)
![screenshot_6](https://user-images.githubusercontent.com/6452991/51682226-26c71b00-1fe7-11e9-9b07-11b0f6a27438.png)

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version 70.0.3538.110 (Official Build) (64-bit)

**Additional context**
null

**Comment by devTeaa** [comment]
This has been fix with e9c3a28d0effc80b4c99cd5ce3eefffcaeb84c38, let me know if it happened again
